"""Seiltanzer Terminal — локальный дашборд поддержки решений.

Показывает вероятность дохождения открытой сделки до тейка раньше стопа,
обогащённую данными опционного рынка. Не сигнальный сервис: каждое число
выводимо из реально полученных данных.
"""

__version__ = "0.1.0"

from .analytics_runtime import install_analytics_runtime as _install_analytics_runtime
_install_analytics_runtime()
del _install_analytics_runtime

from .measurement_runtime import install_measurement_runtime as _install_measurement_runtime
_install_measurement_runtime()
del _install_measurement_runtime

from .g1_dataset_runtime import install_g1_dataset_runtime as _install_g1_dataset_runtime
_install_g1_dataset_runtime()
del _install_g1_dataset_runtime

from .g1_dataset_refinement import install_g1_dataset_refinement as _install_g1_dataset_refinement
_install_g1_dataset_refinement()
del _install_g1_dataset_refinement

from .g1_baseline_runtime import install_g1_baseline_runtime as _install_g1_baseline_runtime
_install_g1_baseline_runtime()
del _install_g1_baseline_runtime

from .g1_baseline_refinement import install_g1_baseline_refinement as _install_g1_baseline_refinement
_install_g1_baseline_refinement()
del _install_g1_baseline_refinement

from .g1_q_evidence_runtime import install_g1_q_evidence_runtime as _install_g1_q_evidence_runtime
_install_g1_q_evidence_runtime()
del _install_g1_q_evidence_runtime

from .g1_q_evidence_refinement import install_g1_q_evidence_refinement as _install_g1_q_evidence_refinement
_install_g1_q_evidence_refinement()
del _install_g1_q_evidence_refinement

from .g1_q_collector import install_g1_q_collector as _install_g1_q_collector
_install_g1_q_collector()
del _install_g1_q_collector

from .g1_q_collector_refinement import install_g1_q_collector_refinement as _install_g1_q_collector_refinement
_install_g1_q_collector_refinement()
del _install_g1_q_collector_refinement

from .g1_shadow_runtime import install_g1_shadow_runtime as _install_g1_shadow_runtime
_install_g1_shadow_runtime()
del _install_g1_shadow_runtime

from .g1_shadow_refinement import install_g1_shadow_refinement as _install_g1_shadow_refinement
_install_g1_shadow_refinement()
del _install_g1_shadow_refinement

from .g1_shadow_artifact_refinement import install_g1_shadow_artifact_refinement as _install_g1_shadow_artifact_refinement
_install_g1_shadow_artifact_refinement()
del _install_g1_shadow_artifact_refinement

from .g1_management_refinement import install_g1_management_refinement as _install_g1_management_refinement
_install_g1_management_refinement()
del _install_g1_management_refinement

from .g1_management_execution_refinement import install_g1_management_execution_refinement as _install_g1_management_execution_refinement
_install_g1_management_execution_refinement()
del _install_g1_management_execution_refinement

from .g1_management_integration import install_g1_management_integration as _install_g1_management_integration
_install_g1_management_integration()
del _install_g1_management_integration

# G.1S / G.1-M.1 add fast research feedback on already-frozen prospective rows.
# They wrap the G.1-M-aware passive scheduler and cannot change production policy.
from .g1_short_horizon_integration import install_g1_short_horizon_integration as _install_g1_short_horizon_integration
_install_g1_short_horizon_integration()
del _install_g1_short_horizon_integration

# New background T0 captures freeze ATR before future outcomes; existing rows are
# never hindsight-enriched. Four ablation feature families remain research-only.
from .g1_short_horizon_refinement import install_g1_short_horizon_refinement as _install_g1_short_horizon_refinement
_install_g1_short_horizon_refinement()
del _install_g1_short_horizon_refinement

# Every shadow fit receives an exact immutable source manifest (T0 + resolution
# hashes). A model cannot later reconstruct or silently change its training set.
from .g1_short_horizon_cut_refinement import install_g1_short_horizon_cut_refinement as _install_g1_short_horizon_cut_refinement
_install_g1_short_horizon_cut_refinement()
del _install_g1_short_horizon_cut_refinement
