"""Seiltanzer Terminal — локальный дашборд поддержки решений.

Показывает вероятность дохождения открытой сделки до тейка раньше стопа,
обогащённую данными опционного рынка. Не сигнальный сервис: каждое число
выводимо из реально полученных данных.
"""

__version__ = "0.1.0"

from .analytics_runtime import install_analytics_runtime as _install_analytics_runtime
_install_analytics_runtime()
del _install_analytics_runtime

from .measurement_runtime import install_measurement_runtime as _install_measurement_runtime
_install_measurement_runtime()
del _install_measurement_runtime

from .g1_dataset_runtime import install_g1_dataset_runtime as _install_g1_dataset_runtime
_install_g1_dataset_runtime()
del _install_g1_dataset_runtime

from .g1_dataset_refinement import install_g1_dataset_refinement as _install_g1_dataset_refinement
_install_g1_dataset_refinement()
del _install_g1_dataset_refinement

from .g1_baseline_runtime import install_g1_baseline_runtime as _install_g1_baseline_runtime
_install_g1_baseline_runtime()
del _install_g1_baseline_runtime

from .g1_baseline_refinement import install_g1_baseline_refinement as _install_g1_baseline_refinement
_install_g1_baseline_refinement()
del _install_g1_baseline_refinement

from .g1_q_evidence_runtime import install_g1_q_evidence_runtime as _install_g1_q_evidence_runtime
_install_g1_q_evidence_runtime()
del _install_g1_q_evidence_runtime

from .g1_q_evidence_refinement import install_g1_q_evidence_refinement as _install_g1_q_evidence_refinement
_install_g1_q_evidence_refinement()
del _install_g1_q_evidence_refinement

from .g1_q_collector import install_g1_q_collector as _install_g1_q_collector
_install_g1_q_collector()
del _install_g1_q_collector

from .g1_q_collector_refinement import install_g1_q_collector_refinement as _install_g1_q_collector_refinement
_install_g1_q_collector_refinement()
del _install_g1_q_collector_refinement

from .g1_shadow_runtime import install_g1_shadow_runtime as _install_g1_shadow_runtime
_install_g1_shadow_runtime()
del _install_g1_shadow_runtime

from .g1_shadow_refinement import install_g1_shadow_refinement as _install_g1_shadow_refinement
_install_g1_shadow_refinement()
del _install_g1_shadow_refinement

from .g1_shadow_artifact_refinement import install_g1_shadow_artifact_refinement as _install_g1_shadow_artifact_refinement
_install_g1_shadow_artifact_refinement()
del _install_g1_shadow_artifact_refinement

from .g1_management_refinement import install_g1_management_refinement as _install_g1_management_refinement
_install_g1_management_refinement()
del _install_g1_management_refinement

from .g1_management_execution_refinement import install_g1_management_execution_refinement as _install_g1_management_execution_refinement
_install_g1_management_execution_refinement()
del _install_g1_management_execution_refinement

from .g1_management_integration import install_g1_management_integration as _install_g1_management_integration
_install_g1_management_integration()
del _install_g1_management_integration

from .g1_short_horizon_integration import install_g1_short_horizon_integration as _install_g1_short_horizon_integration
_install_g1_short_horizon_integration()
del _install_g1_short_horizon_integration

from .g1_short_horizon_refinement import install_g1_short_horizon_refinement as _install_g1_short_horizon_refinement
_install_g1_short_horizon_refinement()
del _install_g1_short_horizon_refinement

from .g1_short_horizon_market_features import install_g1_short_horizon_market_features as _install_g1_short_horizon_market_features
_install_g1_short_horizon_market_features()
del _install_g1_short_horizon_market_features

from .g1_short_horizon_baseline_refinement import install_g1_short_horizon_baseline_refinement as _install_g1_short_horizon_baseline_refinement
_install_g1_short_horizon_baseline_refinement()
del _install_g1_short_horizon_baseline_refinement

from .g1_short_horizon_gbt_refinement import install_g1_short_horizon_gbt_refinement as _install_g1_short_horizon_gbt_refinement
_install_g1_short_horizon_gbt_refinement()
del _install_g1_short_horizon_gbt_refinement

from .g1_short_horizon_cut_refinement import install_g1_short_horizon_cut_refinement as _install_g1_short_horizon_cut_refinement
_install_g1_short_horizon_cut_refinement()
del _install_g1_short_horizon_cut_refinement

from .g1_fast_learning_integrity_refinement import install_g1_fast_learning_integrity_refinement as _install_g1_fast_learning_integrity_refinement
_install_g1_fast_learning_integrity_refinement()
del _install_g1_fast_learning_integrity_refinement

from .g1_short_horizon_metrics_refinement import install_g1_short_horizon_metrics_refinement as _install_g1_short_horizon_metrics_refinement
_install_g1_short_horizon_metrics_refinement()
del _install_g1_short_horizon_metrics_refinement

from .g1_short_horizon_metrics_integrity import install_g1_short_horizon_metrics_integrity as _install_g1_short_horizon_metrics_integrity
_install_g1_short_horizon_metrics_integrity()
del _install_g1_short_horizon_metrics_integrity

from .g1_short_horizon_status_materialization import install_g1_short_horizon_status_materialization as _install_g1_short_horizon_status_materialization
_install_g1_short_horizon_status_materialization()
del _install_g1_short_horizon_status_materialization

from .g1_short_horizon_status_integrity import install_g1_short_horizon_status_integrity as _install_g1_short_horizon_status_integrity
_install_g1_short_horizon_status_integrity()
del _install_g1_short_horizon_status_integrity

from .g1_short_horizon_evidence_completion import install_g1_short_horizon_evidence_completion as _install_g1_short_horizon_evidence_completion
_install_g1_short_horizon_evidence_completion()
del _install_g1_short_horizon_evidence_completion

from .g1_short_horizon_continuous_learning import install_g1_short_horizon_continuous_learning as _install_g1_short_horizon_continuous_learning
_install_g1_short_horizon_continuous_learning()
del _install_g1_short_horizon_continuous_learning

from .g1_short_horizon_calibration import install_g1_short_horizon_calibration as _install_g1_short_horizon_calibration
_install_g1_short_horizon_calibration()
del _install_g1_short_horizon_calibration

from .g1_short_horizon_feature_contract_v2 import install_g1_short_horizon_feature_contract_v2 as _install_g1_short_horizon_feature_contract_v2
_install_g1_short_horizon_feature_contract_v2()
del _install_g1_short_horizon_feature_contract_v2

from .g1_short_horizon_feature_v2_integrity import install_g1_short_horizon_feature_v2_integrity as _install_g1_short_horizon_feature_v2_integrity
_install_g1_short_horizon_feature_v2_integrity()
del _install_g1_short_horizon_feature_v2_integrity

# V2 continuous predictions run after V2 direction and reapply only causal
# pre-T0 calibrators, closing wrapper ordering without touching V1.
from .g1_short_horizon_continuous_v2 import install_g1_short_horizon_continuous_v2 as _install_g1_short_horizon_continuous_v2
_install_g1_short_horizon_continuous_v2()
del _install_g1_short_horizon_continuous_v2

# Presentation snapshots are computed by the low-priority worker; HTTP reads
# frozen JSON instead of triggering full-history OOS scans.
from .g1_short_horizon_evidence_materialization import install_g1_short_horizon_evidence_materialization as _install_g1_short_horizon_evidence_materialization
_install_g1_short_horizon_evidence_materialization()
del _install_g1_short_horizon_evidence_materialization

# Historical diagnostics are true expanding walk-forward folds with fixed-horizon
# purge/embargo. Prospective OOS remains the only evidence allowed to support edge.
from .g1_short_horizon_walkforward import install_g1_short_horizon_walkforward as _install_g1_short_horizon_walkforward
_install_g1_short_horizon_walkforward()
del _install_g1_short_horizon_walkforward
