"""Standalone responsive Intelligence Lab page for Phase G.1E."""
from __future__ import annotations

from fastapi.responses import HTMLResponse


INTELLIGENCE_HTML = r'''<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SEILTANZER · INTELLIGENCE LAB</title>
<style>
:root{--bg:#090d0f;--card:#11181c;--line:#263238;--txt:#d8e3e8;--dim:#77878f;--green:#77d39b;--amber:#e8c56b;--red:#e07a7a;--blue:#7db7d8;--mono:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--txt);font-family:var(--mono);font-size:13px}.wrap{max-width:1500px;margin:auto;padding:18px}.top{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:14px}.brand{font-size:22px;font-weight:800;letter-spacing:.08em}.sub{color:var(--dim);margin-top:5px;line-height:1.5}.nav{display:flex;gap:8px;flex-wrap:wrap}.btn{color:var(--txt);text-decoration:none;border:1px solid var(--line);padding:8px 11px;border-radius:6px;background:#0d1316}.btn:hover{border-color:#58717d}.grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:10px}.card{background:var(--card);border:1px solid var(--line);border-radius:8px;padding:14px;min-width:0}.span3{grid-column:span 3}.span4{grid-column:span 4}.span6{grid-column:span 6}.span8{grid-column:span 8}.span12{grid-column:span 12}.k{color:var(--dim);font-size:11px;letter-spacing:.08em;text-transform:uppercase}.v{font-size:25px;font-weight:700;margin-top:7px}.small{font-size:11px;color:var(--dim);line-height:1.55}.ok{color:var(--green)}.warn{color:var(--amber)}.bad{color:var(--red)}.blue{color:var(--blue)}.headline{font-size:16px;line-height:1.5;margin-top:8px}.bar{height:8px;background:#0a1013;border:1px solid #233239;border-radius:99px;overflow:hidden;margin-top:6px}.fill{height:100%;background:var(--blue)}.model{padding:10px;border:1px solid #223037;border-radius:6px;margin-top:8px}.model-row{display:flex;justify-content:space-between;gap:8px;align-items:center}.pill{font-size:10px;border:1px solid #33454e;border-radius:99px;padding:3px 7px;color:var(--dim)}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:720px}th,td{text-align:left;border-bottom:1px solid #202c31;padding:8px 7px;vertical-align:top}th{color:var(--dim);font-size:10px;letter-spacing:.06em}.reason{display:flex;justify-content:space-between;gap:12px;padding:6px 0;border-bottom:1px dashed #263238}.funnel{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin-top:12px}.funnel>div{text-align:center;border:1px solid #25343b;border-radius:6px;padding:10px 5px}.funnel strong{display:block;font-size:20px;margin-top:5px}.hist{display:flex;align-items:flex-end;gap:4px;height:110px;margin-top:12px}.hist i{display:block;flex:1;min-width:4px;background:#6fa8c6;border-radius:2px 2px 0 0}.svg{width:100%;height:140px;border:1px solid #202d33;background:#0c1215;border-radius:6px;margin-top:10px}.section-title{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:8px}.stamp{color:var(--dim);font-size:10px}.empty{padding:18px 0;color:var(--dim)}.research{border-color:#675b31}.storage-healthy{color:var(--green)}.storage-warning{color:var(--amber)}
@media(max-width:1050px){.span3,.span4{grid-column:span 6}.span6,.span8{grid-column:span 12}.funnel{grid-template-columns:1fr 1fr 1fr}}
@media(max-width:650px){.wrap{padding:10px}.top{display:block}.nav{margin-top:12px}.span3,.span4,.span6,.span8,.span12{grid-column:span 12}.funnel{grid-template-columns:1fr 1fr}.v{font-size:21px}.brand{font-size:18px}}
</style>
</head><body><div class="wrap">
<div class="top"><div><div class="brand">SEILTANZER · INTELLIGENCE LAB</div><div class="sub">Наблюдение → замороженный прогноз → реальный исход → измерение → shadow-обучение → будущий OOS.<br><b>Research only:</b> experimental Q→P не влияет на реальные торговые решения.</div></div><div class="nav"><a class="btn" href="/">← ТЕРМИНАЛ</a><button class="btn" id="refresh">ОБНОВИТЬ</button></div></div>
<div class="grid">
 <section class="card span6 research"><div class="k">INTELLIGENCE STATE</div><div id="maturity" class="v">—</div><div id="headline" class="headline">Загрузка…</div><div id="updated" class="small"></div></section>
 <section class="card span3"><div class="k">Q EXPERIENCE</div><div id="qexp" class="v">—</div><div id="qexpSub" class="small"></div></section>
 <section class="card span3"><div class="k">DATA PROTECTION</div><div id="storage" class="v">—</div><div id="storageSub" class="small"></div></section>
 <section class="card span8"><div class="section-title"><div class="k">Q DATA PIPELINE</div><span class="stamp">prospective only</span></div><div class="funnel" id="funnel"></div></section>
 <section class="card span4"><div class="k">TOP DATA BLOCKERS</div><div id="blockers" class="empty">—</div></section>
 <section class="card span6"><div class="section-title"><div class="k">SHADOW MODELS</div><span class="pill">PRODUCTION AUTHORITY OFF</span></div><div id="models"></div></section>
 <section class="card span6"><div class="section-title"><div class="k">FORECAST QUALITY · TERMINAL Q</div><span class="stamp">G.1B authority</span></div><div id="quality"></div><div class="hist" id="pit"></div></section>
 <section class="card span12"><div class="section-title"><div class="k">WAITING FOR OUTCOME</div><span class="stamp">прогноз уже заморожен; будущего результата ещё нет</span></div><div class="table-wrap"><table><thead><tr><th>ИНСТРУМЕНТ</th><th>T0</th><th>EXPIRY</th><th>RAW Q UP</th><th>ОСТАЛОСЬ</th><th>Q SOURCE</th><th>RELATION</th></tr></thead><tbody id="pending"></tbody></table></div></section>
 <section class="card span12"><div class="section-title"><div class="k">RECENT RESOLVED Q</div><span class="stamp">никакого hindsight recalculation</span></div><div class="table-wrap"><table><thead><tr><th>ИНСТРУМЕНТ</th><th>T0</th><th>RAW Q UP</th><th>РЕЗУЛЬТАТ</th><th>PIT</th><th>CLEAN</th></tr></thead><tbody id="resolved"></tbody></table></div></section>
 <section class="card span12"><div class="section-title"><div class="k">INTELLIGENCE EVOLUTION</div><span class="stamp">6h immutable snapshots</span></div><svg class="svg" id="history" viewBox="0 0 1000 140" preserveAspectRatio="none"></svg><div class="small">Линия показывает рост effective Q evidence. Пока resolved Q = 0, она закономерно лежит у нуля.</div></section>
</div></div>
<script>
const $=s=>document.querySelector(s), fmtN=n=>n==null?'—':Number(n).toLocaleString('ru-RU'), pct=p=>p==null?'—':(Number(p)*100).toFixed(1)+'%', dt=t=>t?new Date(Number(t)*1000).toLocaleString('ru-RU',{hour12:false}):'—';
function dur(sec){if(sec==null)return'—';sec=Math.max(0,Number(sec));if(sec<3600)return Math.round(sec/60)+' мин';if(sec<86400)return(sec/3600).toFixed(1)+' ч';return(sec/86400).toFixed(1)+' д';}
function statusClass(x){x=String(x||'');return /HEALTHY|SUPPORTED|READY/.test(x)?'ok':/WARNING|DEGRADED|STALE|EARLY|PROVISIONAL|LOCAL_BACKUP/.test(x)?'warn':''}
async function get(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(url+' '+r.status);return r.json()}
function renderModels(models){const host=$('#models');host.innerHTML='';for(const name of ['platt','beta','isotonic']){const m=models[name]||{};const d=m.deficits||{};const need=Object.entries(d).filter(([,v])=>v>0).map(([k,v])=>`${k}: +${v}`).slice(0,3).join(' · ');const el=document.createElement('div');el.className='model';el.innerHTML=`<div class="model-row"><b>${name.toUpperCase()}</b><span class="pill ${statusClass(m.status)}">${m.status||'—'}</span></div><div class="small" style="margin-top:6px">${m.ready?'Данных достаточно для shadow fit. OOS ещё не доказан.':(need||'Ожидание evidence')}<br>${(m.explanations||[])[0]||''}</div>`;host.appendChild(el)}}
function renderFunnel(items){const max=Math.max(1,...items.map(x=>Number(x.n)||0));$('#funnel').innerHTML=items.map(x=>`<div><span class="k">${x.name}</span><strong>${fmtN(x.n)}</strong><div class="bar"><div class="fill" style="width:${Math.max(2,(Number(x.n)||0)/max*100)}%"></div></div></div>`).join('')}
function renderBlockers(status,pipeline){const all={...(status.data_quality?.top_q_blockers||{}),...(status.data_quality?.primary_reasons||{})};const rows=Object.entries(all).sort((a,b)=>b[1]-a[1]).slice(0,7);$('#blockers').className=rows.length?'':'empty';$('#blockers').innerHTML=rows.length?rows.map(([k,v])=>`<div class="reason"><span><b>${k}</b><br><span class="small">${pipeline.explanations?.[k]||''}</span></span><strong>${fmtN(v)}</strong></div>`).join(''):'Нет blockers'}
function renderQuality(q){const ti=q.status?.terminal_q_identity||{};const dm=ti.direction_event?.q_identity?.metrics||{};const rel=ti.direction_event?.q_identity?.reliability||{};$('#quality').innerHTML=`<div class="model-row"><span>Q metrics eligible</span><b>${fmtN(ti.metrics_eligible_n||0)}</b></div><div class="model-row"><span>Effective Q N</span><b>${fmtN(ti.effective_q_n||0)}</b></div><div class="model-row"><span>Brier</span><b>${dm.brier==null?'—':Number(dm.brier).toFixed(4)}</b></div><div class="model-row"><span>Log loss</span><b>${dm.log_loss==null?'—':Number(dm.log_loss).toFixed(4)}</b></div><div class="model-row"><span>ECE</span><b>${rel.ece==null?'—':Number(rel.ece).toFixed(4)}</b></div><div class="small" style="margin-top:8px">${ti.metrics_eligible_n?'Training/measurement diagnostics only; edge claim = false.':'Недостаточно завершённых clean Q-наблюдений — числа не выдумываются.'}</div>`;const hist=ti.pit?.histogram||[];const max=Math.max(1,...hist.map(x=>Number(x.n)||0));$('#pit').innerHTML=hist.length?hist.map(x=>`<i title="${x.lower}–${x.upper}: n=${x.n}" style="height:${Math.max(2,(Number(x.n)||0)/max*100)}%"></i>`).join(''):''}
function renderPending(items){$('#pending').innerHTML=items.length?items.map(x=>`<tr><td><b>${x.instrument}</b></td><td>${dt(x.captured_ts)}</td><td>${dt(x.target_ts)}</td><td>${pct(x.raw_q_up)}</td><td>${dur(x.time_remaining_sec)}</td><td>${x.q_source_instrument||'—'}</td><td>${x.relation||x.proxy_transform||'—'}</td></tr>`).join(''):'<tr><td colspan="7" class="empty">Нет pending Q observations</td></tr>'}
function renderResolved(items){$('#resolved').innerHTML=items.length?items.map(x=>`<tr><td><b>${x.instrument}</b></td><td>${dt(x.captured_ts)}</td><td>${pct(x.raw_q_up)}</td><td>${x.future_log_return==null?'—':(Number(x.future_log_return)*100).toFixed(3)+'%'}</td><td>${x.terminal_pit_q==null?'—':Number(x.terminal_pit_q).toFixed(3)}</td><td>${x.terminal_clean===true?'✓':x.terminal_clean===false?'✕':'—'}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">Первые Q forecasts ещё ожидают expiry.</td></tr>'}
function renderHistory(items){const svg=$('#history');if(!items.length){svg.innerHTML='';return}const vals=items.map(x=>Number(x.snapshot?.experience?.q_effective_n)||0), max=Math.max(1,...vals);const pts=vals.map((v,i)=>`${items.length===1?500:i/(items.length-1)*980+10},${125-v/max*105}`).join(' ');svg.innerHTML=`<line x1="10" y1="125" x2="990" y2="125" stroke="#263238"/><polyline points="${pts}" fill="none" stroke="#77d39b" stroke-width="3" vector-effect="non-scaling-stroke"/>`}
async function load(){try{const [s,p,q,c,pend,res,h]=await Promise.all([get('/api/research/g1/intelligence/status'),get('/api/research/g1/intelligence/pipeline'),get('/api/research/g1/intelligence/forecast-quality'),get('/api/research/g1/intelligence/calibration'),get('/api/research/g1/intelligence/pending?limit=50'),get('/api/research/g1/intelligence/resolved?limit=50'),get('/api/research/g1/intelligence/history?limit=200')]);$('#maturity').textContent=s.maturity_state;$('#maturity').className='v '+statusClass(s.maturity_state);$('#headline').textContent=s.headline;$('#updated').textContent='Обновлено: '+new Date().toLocaleTimeString('ru-RU');const e=s.experience||{};$('#qexp').textContent=`${fmtN(e.q_captured)} / ${fmtN(e.q_resolved)}`;$('#qexpSub').textContent=`captured / resolved · eligible ${fmtN(e.q_clean_eligible)} · effective N ${fmtN(e.q_effective_n)}`;const st=s.storage||{};$('#storage').textContent=st.health||'NO STORAGE STATUS';$('#storage').className='v '+statusClass(st.health);$('#storageSub').textContent=`DB integrity: ${st.sqlite_integrity?.ok?'PASS':'FAIL'} · local backup: ${dur(st.last_local_backup_age_sec)} ago · off-host: ${st.offhost_configured?(st.last_offhost_backup?'configured':'waiting'):'not configured'}`;renderFunnel(p.funnel||[]);renderBlockers(s,p);renderModels(s.models||{});renderQuality(q);renderPending(pend.items||[]);renderResolved(res.items||[]);renderHistory(h.items||[])}catch(e){console.error(e);$('#headline').textContent='Не удалось загрузить Intelligence API: '+e.message}}
$('#refresh').onclick=load;load();setInterval(load,60000);
</script></body></html>'''


def intelligence_page() -> HTMLResponse:
    return HTMLResponse(INTELLIGENCE_HTML)
