"""Exact, compact playbooks transcribed from Strategy Premium Edition (2).pdf."""

PLAYBOOKS = {
    1: dict(timeframes="8H/1H(55m)", premise="8H FVG tested but not fully filled; sweep + 1H AMD",
            entry="return to manipulation and confirmed reversal",
            target="Fib 0.786: local structure to first 8H test candle",
            invalidation="manual loss of the 8H FVG/AMD structure",
            recovery="2H FVG sweep + 15m AMD/return"),
    2: dict(timeframes="1W/1H", premise="Weekly FVG 0.786 + 1H AMD",
            entry="touch/reaction at 0.786 after AMD confirmation",
            target="Fib 0.786: local liquidity to Weekly structure",
            invalidation="manual loss of Weekly FVG/Fib structure",
            recovery="1D FVG 0.786 + 15m AMD"),
    3: dict(timeframes="12H/4H/15m", premise="untested 12H FVG + 4H bFVGc",
            entry="15m bullish body close above 4H bFVGc; if close >0.38, entry at 0.236",
            target="Fib 0.118",
            invalidation="stop >0.11 cancels; stop >0.15 shifts target; manual loss of 12H zone",
            recovery="3H FVG + 1H bFVGc + 4m confirmation; apply recovery caps"),
    4: dict(timeframes="1D/4H/15m", premise="NAS100 1D FVG + 4H wick test; SP500 liquidity sweep",
            entry="15m SP500 return; simultaneous NAS/SP confirmation is A+",
            target="2.5R per setup geometry",
            invalidation="SP500 confirmation absent or sustained cross-index divergence",
            recovery="6H FVG + 1H sweep + 4m return"),
    5: dict(timeframes="12H", premise="SP500 12H FVG retest with VIX >20",
            entry="confirmed reaction from the retested 12H FVG",
            target="third local FVG across 4H/3H/2H/1H",
            invalidation="loss of FVG or required VIX context",
            recovery="manual recovery pattern from strategy"),
    6: dict(timeframes="8H", premise="US30 8H FVG test with VIX >20",
            entry="confirmed reaction from 8H FVG",
            target="2.5R per setup geometry",
            invalidation="loss of 8H FVG or required VIX context; max two positions",
            recovery="manual recovery pattern from strategy"),
    7: dict(timeframes="12H/1H", premise="GER40 12H FVG sweep + untested 1H FVG; DV1X <19 mandatory",
            entry="1H FVG reaction confirms the 12H sweep",
            target="Fib 0.786 from sweep to maximum 1H FVG",
            invalidation="DV1X filter fails or 1H confirmation is lost",
            recovery="manual GER40 lower-timeframe recovery"),
    8: dict(timeframes="12H/2H/90m/1H", premise="12H FVG + 2H bFVGc + 90m FVG alignment",
            entry="body close above 2H bFVGc below 0.38; if above, dive below 0.236 then 1H reclaim",
            target="Fib 0.786",
            invalidation="loss of the aligned FVG/bFVGc structure",
            recovery="3H FVG + 30m bFVGc + 22m FVG; same 0.38/0.236 rule"),
    9: dict(timeframes="12H/2H/1H", premise="UK100 12H FVG + 2H bFVGc",
            entry="first 1H body close above bFVGc; above 0.38 use limit at 0.236",
            target="2.5R per setup geometry",
            invalidation="stop <0.17% cancels",
            recovery="3H FVG + 30m bFVGc; 15m entry; stop <0.04% cancels"),
    10: dict(timeframes="1D/4H/1H", premise="JPY100 1D FVG + 1H AMD/liquidity",
             entry="4H wick sweep",
             target="Fib 0.786 of AMD structure",
             invalidation="manual loss of Daily FVG/AMD structure",
             recovery="6H FVG + 15m liquidity + 1H wick sweep"),
    11: dict(timeframes="4H", premise="XAU volatility correlation: VIX touches then exceeds 21.25 while GVZ <18",
             entry="long after VIX returns below 21.25 while GVZ remains <18",
             target="2.7R",
             invalidation="required VIX/GVZ sequence fails; stop beyond 4H low, risk <=1.5% account",
             recovery="none specified"),
    12: dict(timeframes="12H/15m", premise="XAU 12H FVG sweep/retest",
             entry="15m return above sweep location",
             target="2.5R per setup geometry",
             invalidation="15m return fails and 12H structure is lost",
             recovery="3H FVG sweep/retest + 3–4m return"),
    13: dict(timeframes="1D/4H/1H", premise="XAG 1D FVG + 1H AMD/liquidity",
             entry="4H wick sweep at Fib 0.5 inside 1.0–0.786 Daily FVG",
             target="Fib 0.786 of AMD structure",
             invalidation="normal order flow, no AMD/liquidity, or 1D FVG too small",
             recovery="6H FVG + 15m liquidity + 1H wick sweep at Fib 0.5"),
    14: dict(timeframes="1D/4H/20m", premise="EURUSD Daily FVG + inverse DXY FVG confirmation",
             entry="EURUSD in 1D FVG and DXY in untested 20m FVG after 4H zones are tested",
             target="second distant FVG on 4H/3H/2H/1H/30m",
             invalidation="stop must be >0.14%; DXY confirmation or Daily structure lost",
             recovery="EUR 6H FVG + DXY 1H/5m FVG; same >0.14% stop rule"),
    15: dict(timeframes="1D/4H/10m", premise="bearish EURUSD 1D FVG + bullish DXY 4H FVG",
             entry="simultaneous 4H zone touch then 10m return below lower 1D FVG boundary",
             target="2.5R per setup geometry",
             invalidation="stop outside 0.25–0.79% or paired confirmation lost",
             recovery="EUR 6H bearish FVG + DXY 1H long FVG; 2–3m return; stop >=0.06%"),
    16: dict(timeframes="8H/4H", premise="USDCAD 8H bearish candle + FVG; price takes formation high",
             entry="4H Fib to second candle: 0.236; if close below, formation low",
             target="Fib from low +0.618 to formation high; exit at 0.118",
             invalidation="compression before entry cancels",
             recovery="2H block + 1H confirmation with the same Fib/compression rules"),
}
